fragment ImageFragment on Image {
  id
  url
  caption
  createdAt
  location {
    id
    name
  }
  people {
    id
    username
    displayName
    profilePicture {
      id
      url
    }
  }
  owner {
    id
    username
    displayName
    profilePicture {
      id
      url
    }
  }
}
