fragment UserFragment on User {
  id
  username
  displayName
  profilePicture {
    id
    url,
    createdAt
    owner {
      id
      username
      displayName
      profilePicture {
        id,
        url
      }
    }
  }
}
